### ISSUE TITLE
About timestamp for utterances

### ISSUE THREAD

**Issue by oyly16** [sangmin-git/MMSI#1]
Thank you for the wonderful work of MMSI!

I am very interested in this research project. I downloaded the dataset and I noticed that there is only one timestamp, which should be the start of each utterance. I am wondering

Q1. how can I get the end timestamp of each sentence? If there is no annotation, I hope I can get some advices.
Q2. How to sample T frames corresponded with an utterance? In Section 5.1 of the paper, the implementation is "We leverage about 3 seconds of video frames (frame interval 0.4s) that correspond to the timeline of the utterance." Does this mean the sample is [startTime:(startTime+3):0.4]?
Q3. if the sample in Q2 is [startTime:(startTime+3):0.4], is it possible that these video frames contained the next utterance?
For example, this is annotations in Flashback##ONE#NIGHT#ULTIMATE#WEREWOLF##Retro#9_Game1.txt, line 19-20:
'''
Mitchell (01:52): Well, I can tell you.
Paul (01:53): Mitchell, if you want to talk, now you go ahead.
'''
When conducting T frames of Mitchell(01:52)'s utterance, is it possible that Paul(01:53)'s utterance is also sampled?

Thanks again for the fantastic work!

**Comment by sangmin-git** [comment]
Hi, thanks for your interests in our work. 

A1. There is no end timestamp of each sentence in the dataset. You can consider using a speech model to extract this information.
A2. In terms of your expression, we used like [startTime-1:startTime+2:0.4]. 
We encoded the visual features starting 1 second before the start stamp because the timestamps are based on 1-second unit and may not reflect the exact start time. 
A3. You are right, there is a possibility that the visual features contain the temporal region for the next utterance. However, we encode motion for the speaker of a given current utterance, so motion for the next speaker is automatically neglected in the current inference.

**Comment by oyly16** [comment]
Thank you for the response! The answers well addressed my concerns.
